#!/usr/bin/env python3
"""Deterministic generator: docs/registers/pages.yml -> docs/DOCUMENTATION_CROSSWALK.md.

Release 0.11.0 · P3 (decision D1). The crosswalk is a GENERATED human-readable view of the canonical
register. Run with no args to write the crosswalk; run with ``--check`` to verify the on-disk file
matches a fresh render (non-zero exit on drift). Output is deterministic: stable ordering, no
timestamps, and every value comes from pages.yml (no manual-only data).
"""
from __future__ import annotations

import io
import os
import sys

import yaml

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SRC = os.path.join(ROOT, "docs", "registers", "pages.yml")
OUT = os.path.join(ROOT, "docs", "DOCUMENTATION_CROSSWALK.md")

NODE_TITLES = {
    "00": "00 · Company Home", "01": "01 · How This Manual Works",
    "10": "10 · Client-Facing Operations", "20": "20 · Technology & Infrastructure",
    "30": "30 · Business Operations", "40": "40 · Cross-Platform & Shared",
    "80": "80 · Libraries & Programs", "90": "90 · Registers & Governance",
}


def cell(v):
    if v is None:
        return "—"
    return str(v).replace("|", "\\|").replace("\n", " ")


def home(r):
    if r["canonical_source"] == "git":
        return f"git:`{cell(r['repository_path'])}`"
    if r["canonical_source"] == "generated":
        return f"generated:`{cell(r['repository_path'])}`"
    if r["canonical_source"] == "legacy_unresolved":
        return f"legacy:`{cell(r['confluence_page_id'])}` (non-canonical)"
    return f"confluence:`{cell(r['confluence_page_id'])}`"


def render(doc) -> str:
    pages = doc["pages"]
    b = io.StringIO()
    b.write("<!-- GENERATED FILE — DO NOT EDIT BY HAND.\n")
    b.write("     Source of truth: docs/registers/pages.yml (canonical Publication Register).\n")
    b.write("     Regenerate: python3 scripts/registers/gen_crosswalk.py\n")
    b.write("     Validate:   python3 scripts/registers/validate_register.py -->\n\n")
    b.write("# Documentation Crosswalk — 360 Wealth Consulting Operations Manual\n\n")
    b.write("_Generated human-readable view of the canonical machine-readable Publication Register_\n")
    b.write("_(`docs/registers/pages.yml`). Do not edit this file directly — edit the register and_\n")
    b.write("_regenerate. Per **DEC-001 / decision D1**, `pages.yml` is the single source of truth._\n\n")
    b.write(f"**Total register rows:** {len(pages)}\n\n")

    # summary counts (all derived from pages.yml)
    def counts(field):
        c = {}
        for r in pages:
            c[r[field]] = c.get(r[field], 0) + 1
        return " · ".join(f"{k}: {v}" for k, v in sorted(c.items()))

    b.write(f"**By status:** {counts('status')}  \n")
    b.write(f"**By canonical source:** {counts('canonical_source')}  \n")
    b.write(f"**By compliance gate:** {counts('compliance_gate')}\n\n")

    # D10 taxonomy migration legend
    b.write("## D10 taxonomy migration (legacy crosswalk letter → framework area)\n\n")
    b.write("| Letter | Area | Note |\n|---|---|---|\n")
    for m in doc.get("taxonomy_migration_d10", []):
        b.write(f"| {m['letter']} | `{m['area']}` | {cell(m['note'])} |\n")
    b.write("\n")

    # grouped by node → area
    order = sorted(pages, key=lambda r: (r["node"] or "zz", r["area"], r["doc_type"], r["page_id"]))
    cur_node = cur_area = None
    for r in order:
        if r["node"] != cur_node:
            cur_node = r["node"]
            cur_area = None
            b.write(f"\n## {NODE_TITLES.get(cur_node, 'Node ' + str(cur_node))}\n")
        if r["area"] != cur_area:
            cur_area = r["area"]
            b.write(f"\n### Area `{cur_area}`\n\n")
            b.write("| page_id | title | type | canonical home | status | gate | owner | "
                    "reviewer | legacy | reconciliation |\n")
            b.write("|---|---|---|---|---|---|---|---|---|---|\n")
        b.write("| `{pid}` | {title} | {dt} | {home} | {st} | {gate} | {owner} | {rev} | "
                "{leg} | {rec} |\n".format(
                    pid=cell(r["page_id"]), title=cell(r["title"]), dt=cell(r["doc_type"]),
                    home=home(r), st=cell(r["status"]), gate=cell(r["compliance_gate"]),
                    owner=cell(r["owner"]), rev=cell(r["reviewer"]),
                    leg=cell(r["legacy_identifier"]), rec=cell(r["reconciliation_status"])))
    b.write("\n")
    return b.getvalue()


def main():
    with open(SRC, encoding="utf-8") as fh:
        doc = yaml.safe_load(fh)
    out = render(doc)
    if "--check" in sys.argv:
        cur = open(OUT, encoding="utf-8").read() if os.path.exists(OUT) else ""
        if cur != out:
            print("DRIFT: DOCUMENTATION_CROSSWALK.md is not up to date with pages.yml", file=sys.stderr)
            sys.exit(1)
        print("crosswalk is current")
        return
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(out)
    print(f"wrote {OUT} ({len(doc['pages'])} rows)")


if __name__ == "__main__":
    main()
