"""Add match review decisions

Revision ID: 53802af14074
Revises: 5baa24cbdc65
Create Date: 2026-07-12 09:45:33.632440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53802af14074'
down_revision: Union[str, Sequence[str], None] = '5baa24cbdc65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_review_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_key', sa.String(length=64), nullable=False),
    sa.Column('record_ids', sa.JSON(), nullable=False),
    sa.Column('decision', sa.String(length=50), nullable=False),
    sa.Column('reviewed_by', sa.String(length=255), nullable=True),
    sa.Column('decision_notes', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match_review_decisions')
    # ### end Alembic commands ###
