"""Add Microsoft unmatched message queue

Revision ID: 753c04edab33
Revises: 3ca741f2d686
Create Date: 2026-07-13 18:09:21.416363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '753c04edab33'
down_revision: Union[str, Sequence[str], None] = '3ca741f2d686'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('microsoft_unmatched_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('microsoft_message_id', sa.String(length=500), nullable=False),
    sa.Column('sender_name', sa.String(length=255), nullable=True),
    sa.Column('sender_address', sa.String(length=320), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('body_preview', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('web_link', sa.Text(), nullable=True),
    sa.Column('has_attachments', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('status', sa.String(length=50), server_default='pending', nullable=False),
    sa.Column('matched_person_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['matched_person_id'], ['people.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('microsoft_message_id', name='uq_microsoft_unmatched_message_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('microsoft_unmatched_messages')
    # ### end Alembic commands ###
