"""add workflow and process automation

Revision ID: e530f5b3d4e5
Revises: d420f4a2c3d4
"""
from datetime import datetime, timezone
from alembic import op
import sqlalchemy as sa

revision = "e530f5b3d4e5"
down_revision = "d420f4a2c3d4"
branch_labels = None
depends_on = None

TEMPLATES = (
    ("prospecting", "Prospecting", "growth"), ("client_onboarding", "Client Onboarding", "client_service"),
    ("schwab_account_opening", "Schwab Account Opening", "operations"), ("asset_transfer", "Asset Transfer", "operations"),
    ("annual_review", "Annual Review", "advice"), ("tax_preparation", "Tax Preparation", "tax"),
    ("tax_extension", "Tax Extension", "tax"), ("irs_notice", "IRS Notice", "tax"),
    ("estate_planning", "Estate Planning", "planning"), ("insurance_review", "Insurance Review", "planning"),
    ("client_termination", "Client Termination", "client_service"), ("compliance_review", "Compliance Review", "compliance"),
)

def upgrade():
    op.create_table("workflow_templates", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("code", sa.String(100), nullable=False), sa.Column("version", sa.Integer(), nullable=False), sa.Column("name", sa.String(255), nullable=False), sa.Column("category", sa.String(100), nullable=False), sa.Column("description", sa.Text()), sa.Column("status", sa.String(30), nullable=False, server_default="draft"), sa.Column("default_sla_hours", sa.Integer()), sa.Column("trigger_config", sa.JSON(), nullable=False, server_default="{}"), sa.Column("created_by_user_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="SET NULL")), sa.Column("published_at", sa.DateTime(timezone=True)), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()), sa.UniqueConstraint("code", "version", name="uq_workflow_template_version"))
    op.create_table("workflow_template_steps", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("template_id", sa.Integer(), sa.ForeignKey("workflow_templates.id", ondelete="CASCADE"), nullable=False), sa.Column("step_key", sa.String(100), nullable=False), sa.Column("name", sa.String(255), nullable=False), sa.Column("sequence", sa.Integer(), nullable=False), sa.Column("step_type", sa.String(30), nullable=False, server_default="task"), sa.Column("execution_mode", sa.String(30), nullable=False, server_default="sequential"), sa.Column("condition", sa.JSON(), nullable=False, server_default="{}"), sa.Column("assignment_config", sa.JSON(), nullable=False, server_default="{}"), sa.Column("queue_code", sa.String(100)), sa.Column("sla_hours", sa.Integer()), sa.Column("requires_independent_approval", sa.Boolean(), nullable=False, server_default="false"), sa.Column("automation_action", sa.String(100)), sa.Column("configuration", sa.JSON(), nullable=False, server_default="{}"), sa.UniqueConstraint("template_id", "step_key", name="uq_workflow_template_step_key"))
    op.create_table("workflow_step_dependencies", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("step_id", sa.Integer(), sa.ForeignKey("workflow_template_steps.id", ondelete="CASCADE"), nullable=False), sa.Column("depends_on_step_id", sa.Integer(), sa.ForeignKey("workflow_template_steps.id", ondelete="CASCADE"), nullable=False), sa.Column("dependency_type", sa.String(30), nullable=False, server_default="completion"), sa.Column("condition", sa.JSON(), nullable=False, server_default="{}"), sa.UniqueConstraint("step_id", "depends_on_step_id", name="uq_workflow_step_dependency"), sa.CheckConstraint("step_id <> depends_on_step_id", name="ck_workflow_no_self_dependency"))
    for name, column in (("template_id", sa.Column("template_id", sa.Integer())), ("template_version", sa.Column("template_version", sa.Integer())), ("template_snapshot", sa.Column("template_snapshot", sa.JSON(), nullable=False, server_default="{}")), ("launched_by_user_id", sa.Column("launched_by_user_id", sa.Integer())), ("idempotency_key", sa.Column("idempotency_key", sa.String(255))), ("paused_at", sa.Column("paused_at", sa.DateTime(timezone=True))), ("cancelled_at", sa.Column("cancelled_at", sa.DateTime(timezone=True))), ("status_reason", sa.Column("status_reason", sa.Text()))): op.add_column("workflow_instances", column)
    op.create_foreign_key("fk_workflow_instance_template", "workflow_instances", "workflow_templates", ["template_id"], ["id"], ondelete="RESTRICT")
    op.create_foreign_key("fk_workflow_instance_launcher", "workflow_instances", "users", ["launched_by_user_id"], ["id"], ondelete="SET NULL")
    op.create_unique_constraint("uq_workflow_instance_idempotency", "workflow_instances", ["idempotency_key"])
    for name, column in (("template_step_id", sa.Column("template_step_id", sa.Integer())), ("definition_snapshot", sa.Column("definition_snapshot", sa.JSON(), nullable=False, server_default="{}")), ("activated_at", sa.Column("activated_at", sa.DateTime(timezone=True))), ("paused_at", sa.Column("paused_at", sa.DateTime(timezone=True))), ("cancelled_at", sa.Column("cancelled_at", sa.DateTime(timezone=True))), ("condition_result", sa.Column("condition_result", sa.Boolean())), ("automation_status", sa.Column("automation_status", sa.String(30)))): op.add_column("workflow_steps", column)
    op.create_foreign_key("fk_workflow_step_template", "workflow_steps", "workflow_template_steps", ["template_step_id"], ["id"], ondelete="SET NULL")
    op.add_column("work_approvals", sa.Column("workflow_step_id", sa.Integer()))
    op.add_column("work_approvals", sa.Column("requires_independent_approver", sa.Boolean(), nullable=False, server_default="false"))
    op.create_foreign_key("fk_work_approval_step", "work_approvals", "workflow_steps", ["workflow_step_id"], ["id"], ondelete="CASCADE")
    op.create_check_constraint("ck_work_approval_segregation", "work_approvals", "NOT requires_independent_approver OR approver_user_id IS NULL OR requested_by_user_id IS NULL OR approver_user_id <> requested_by_user_id")
    op.create_table("workflow_events", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("workflow_instance_id", sa.Integer(), sa.ForeignKey("workflow_instances.id", ondelete="CASCADE"), nullable=False), sa.Column("workflow_step_id", sa.Integer(), sa.ForeignKey("workflow_steps.id", ondelete="CASCADE")), sa.Column("event_type", sa.String(100), nullable=False), sa.Column("idempotency_key", sa.String(255), nullable=False, unique=True), sa.Column("payload", sa.JSON(), nullable=False, server_default="{}"), sa.Column("actor_user_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="SET NULL")), sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()))
    op.create_table("automation_triggers", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("name", sa.String(255), nullable=False), sa.Column("event_type", sa.String(100), nullable=False), sa.Column("entity_type", sa.String(50)), sa.Column("conditions", sa.JSON(), nullable=False, server_default="{}"), sa.Column("template_code", sa.String(100), nullable=False), sa.Column("priority", sa.Integer(), nullable=False, server_default="100"), sa.Column("active", sa.Boolean(), nullable=False, server_default="true"), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()), sa.UniqueConstraint("name", "event_type", name="uq_automation_trigger_name_event"))
    op.create_table("automation_actions", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("workflow_instance_id", sa.Integer(), sa.ForeignKey("workflow_instances.id", ondelete="CASCADE"), nullable=False), sa.Column("workflow_step_id", sa.Integer(), sa.ForeignKey("workflow_steps.id", ondelete="CASCADE")), sa.Column("action_type", sa.String(100), nullable=False), sa.Column("idempotency_key", sa.String(255), nullable=False, unique=True), sa.Column("status", sa.String(30), nullable=False, server_default="pending"), sa.Column("input", sa.JSON(), nullable=False, server_default="{}"), sa.Column("output", sa.JSON(), nullable=False, server_default="{}"), sa.Column("attempts", sa.Integer(), nullable=False, server_default="0"), sa.Column("last_error", sa.Text()), sa.Column("executed_at", sa.DateTime(timezone=True)), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()))
    op.create_table("workflow_escalations", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("workflow_instance_id", sa.Integer(), sa.ForeignKey("workflow_instances.id", ondelete="CASCADE"), nullable=False), sa.Column("workflow_step_id", sa.Integer(), sa.ForeignKey("workflow_steps.id", ondelete="CASCADE")), sa.Column("escalation_type", sa.String(50), nullable=False), sa.Column("level", sa.Integer(), nullable=False, server_default="1"), sa.Column("status", sa.String(30), nullable=False, server_default="open"), sa.Column("due_at", sa.DateTime(timezone=True), nullable=False), sa.Column("assigned_user_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="SET NULL")), sa.Column("assigned_team_id", sa.Integer(), sa.ForeignKey("teams.id", ondelete="SET NULL")), sa.Column("resolved_at", sa.DateTime(timezone=True)), sa.Column("metadata", sa.JSON(), nullable=False, server_default="{}"), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()), sa.UniqueConstraint("workflow_step_id", "escalation_type", "level", name="uq_workflow_escalation"))
    bind = op.get_bind(); now = datetime.now(timezone.utc)
    capability_id = bind.execute(sa.text("INSERT INTO capabilities (code, description, sensitive) VALUES ('work.approve', 'Independently approve workflow work.', true) RETURNING id")).scalar_one()
    bind.execute(sa.text("INSERT INTO role_capabilities (role_id, capability_id) SELECT id, :capability FROM roles WHERE code IN ('administrator', 'compliance')"), {"capability": capability_id})
    templates = sa.table("workflow_templates", sa.column("id", sa.Integer), sa.column("code", sa.String), sa.column("version", sa.Integer), sa.column("name", sa.String), sa.column("category", sa.String), sa.column("status", sa.String), sa.column("default_sla_hours", sa.Integer), sa.column("published_at", sa.DateTime(timezone=True)))
    steps = sa.table("workflow_template_steps", sa.column("template_id", sa.Integer), sa.column("step_key", sa.String), sa.column("name", sa.String), sa.column("sequence", sa.Integer), sa.column("step_type", sa.String), sa.column("execution_mode", sa.String), sa.column("sla_hours", sa.Integer), sa.column("requires_independent_approval", sa.Boolean))
    for code, name, category in TEMPLATES:
        template_id = bind.execute(templates.insert().values(code=code, version=1, name=name, category=category, status="published", default_sla_hours=120, published_at=now).returning(templates.c.id)).scalar_one()
        bind.execute(steps.insert(), [{"template_id": template_id, "step_key": "intake", "name": "Intake and validate", "sequence": 10, "step_type": "task", "execution_mode": "sequential", "sla_hours": 24, "requires_independent_approval": False}, {"template_id": template_id, "step_key": "execute", "name": "Complete required work", "sequence": 20, "step_type": "task", "execution_mode": "parallel", "sla_hours": 72, "requires_independent_approval": False}, {"template_id": template_id, "step_key": "approval", "name": "Independent review and approval", "sequence": 30, "step_type": "approval", "execution_mode": "sequential", "sla_hours": 24, "requires_independent_approval": True}, {"template_id": template_id, "step_key": "delivery", "name": "Deliver and archive", "sequence": 40, "step_type": "task", "execution_mode": "sequential", "sla_hours": 24, "requires_independent_approval": False}])
        ids = {row.step_key: row.id for row in bind.execute(sa.text("SELECT id, step_key FROM workflow_template_steps WHERE template_id = :id"), {"id": template_id})}
        bind.execute(sa.text("INSERT INTO workflow_step_dependencies (step_id, depends_on_step_id, dependency_type, condition) VALUES (:step, :dependency, 'completion', '{}')"), [{"step": ids["execute"], "dependency": ids["intake"]}, {"step": ids["approval"], "dependency": ids["execute"]}, {"step": ids["delivery"], "dependency": ids["approval"]}])
    op.execute("CREATE FUNCTION prevent_workflow_event_mutation() RETURNS trigger AS $$ BEGIN RAISE EXCEPTION 'workflow_events are append-only'; END; $$ LANGUAGE plpgsql")
    op.execute("CREATE TRIGGER workflow_events_immutable BEFORE UPDATE OR DELETE ON workflow_events FOR EACH ROW EXECUTE FUNCTION prevent_workflow_event_mutation()")
    op.execute("CREATE FUNCTION protect_published_workflow_template() RETURNS trigger AS $$ BEGIN IF OLD.status = 'published' THEN RAISE EXCEPTION 'published workflow templates are immutable; create a new version'; END IF; RETURN NEW; END; $$ LANGUAGE plpgsql")
    op.execute("CREATE TRIGGER workflow_templates_published_immutable BEFORE UPDATE OR DELETE ON workflow_templates FOR EACH ROW EXECUTE FUNCTION protect_published_workflow_template()")
    op.execute("CREATE FUNCTION protect_published_workflow_definition() RETURNS trigger AS $$ DECLARE tid integer; BEGIN IF TG_OP = 'DELETE' THEN tid := OLD.template_id; ELSE tid := NEW.template_id; END IF; IF EXISTS (SELECT 1 FROM workflow_templates WHERE id = tid AND status = 'published') THEN RAISE EXCEPTION 'published workflow definitions are immutable; create a new version'; END IF; IF TG_OP = 'DELETE' THEN RETURN OLD; END IF; RETURN NEW; END; $$ LANGUAGE plpgsql")
    op.execute("CREATE TRIGGER workflow_template_steps_published_immutable BEFORE INSERT OR UPDATE OR DELETE ON workflow_template_steps FOR EACH ROW EXECUTE FUNCTION protect_published_workflow_definition()")
    op.execute("CREATE FUNCTION validate_workflow_dependency() RETURNS trigger AS $$ DECLARE step_template integer; dependency_template integer; BEGIN SELECT template_id INTO step_template FROM workflow_template_steps WHERE id = NEW.step_id; SELECT template_id INTO dependency_template FROM workflow_template_steps WHERE id = NEW.depends_on_step_id; IF step_template IS DISTINCT FROM dependency_template THEN RAISE EXCEPTION 'workflow dependency steps must belong to the same template version'; END IF; IF EXISTS (WITH RECURSIVE chain(id) AS (SELECT depends_on_step_id FROM workflow_step_dependencies WHERE step_id = NEW.depends_on_step_id UNION SELECT d.depends_on_step_id FROM workflow_step_dependencies d JOIN chain c ON d.step_id = c.id) SELECT 1 FROM chain WHERE id = NEW.step_id) THEN RAISE EXCEPTION 'circular workflow dependency detected'; END IF; IF EXISTS (SELECT 1 FROM workflow_templates WHERE id = step_template AND status = 'published') THEN RAISE EXCEPTION 'published workflow definitions are immutable; create a new version'; END IF; RETURN NEW; END; $$ LANGUAGE plpgsql")
    op.execute("CREATE TRIGGER workflow_dependencies_valid BEFORE INSERT OR UPDATE ON workflow_step_dependencies FOR EACH ROW EXECUTE FUNCTION validate_workflow_dependency()")
    op.execute("CREATE FUNCTION protect_published_workflow_dependency_delete() RETURNS trigger AS $$ BEGIN IF EXISTS (SELECT 1 FROM workflow_template_steps s JOIN workflow_templates t ON t.id=s.template_id WHERE s.id=OLD.step_id AND t.status='published') THEN RAISE EXCEPTION 'published workflow definitions are immutable; create a new version'; END IF; RETURN OLD; END; $$ LANGUAGE plpgsql")
    op.execute("CREATE TRIGGER workflow_dependencies_delete_immutable BEFORE DELETE ON workflow_step_dependencies FOR EACH ROW EXECUTE FUNCTION protect_published_workflow_dependency_delete()")

def downgrade():
    op.execute("DROP TRIGGER IF EXISTS workflow_dependencies_delete_immutable ON workflow_step_dependencies"); op.execute("DROP FUNCTION IF EXISTS protect_published_workflow_dependency_delete()")
    op.execute("DROP TRIGGER IF EXISTS workflow_dependencies_valid ON workflow_step_dependencies"); op.execute("DROP FUNCTION IF EXISTS validate_workflow_dependency()")
    op.execute("DROP TRIGGER IF EXISTS workflow_template_steps_published_immutable ON workflow_template_steps"); op.execute("DROP FUNCTION IF EXISTS protect_published_workflow_definition()")
    op.execute("DROP TRIGGER IF EXISTS workflow_templates_published_immutable ON workflow_templates"); op.execute("DROP FUNCTION IF EXISTS protect_published_workflow_template()")
    op.execute("DROP TRIGGER IF EXISTS workflow_events_immutable ON workflow_events"); op.execute("DROP FUNCTION IF EXISTS prevent_workflow_event_mutation()")
    for name in ("workflow_escalations", "automation_actions", "automation_triggers", "workflow_events"): op.drop_table(name)
    op.drop_constraint("ck_work_approval_segregation", "work_approvals", type_="check"); op.drop_constraint("fk_work_approval_step", "work_approvals", type_="foreignkey")
    op.drop_column("work_approvals", "requires_independent_approver"); op.drop_column("work_approvals", "workflow_step_id")
    op.drop_constraint("fk_workflow_step_template", "workflow_steps", type_="foreignkey")
    for name in ("automation_status", "condition_result", "cancelled_at", "paused_at", "activated_at", "definition_snapshot", "template_step_id"): op.drop_column("workflow_steps", name)
    op.drop_constraint("uq_workflow_instance_idempotency", "workflow_instances", type_="unique"); op.drop_constraint("fk_workflow_instance_launcher", "workflow_instances", type_="foreignkey"); op.drop_constraint("fk_workflow_instance_template", "workflow_instances", type_="foreignkey")
    for name in ("status_reason", "cancelled_at", "paused_at", "idempotency_key", "launched_by_user_id", "template_snapshot", "template_version", "template_id"): op.drop_column("workflow_instances", name)
    for name in ("workflow_step_dependencies", "workflow_template_steps", "workflow_templates"): op.drop_table(name)
    op.execute("DELETE FROM role_capabilities WHERE capability_id IN (SELECT id FROM capabilities WHERE code = 'work.approve')")
    op.execute("DELETE FROM capabilities WHERE code = 'work.approve'")
