"""add client portal and secure collaboration

Revision ID: f640a6c4e5f6
Revises: e530f5b3d4e5
"""
from alembic import op
import sqlalchemy as sa

revision = "f640a6c4e5f6"
down_revision = "e530f5b3d4e5"
branch_labels = None
depends_on = None

TABLES = (
    "portal_accounts", "portal_access_grants", "portal_invitations", "portal_auth_tokens",
    "portal_devices", "portal_sessions", "portal_threads", "portal_thread_participants",
    "portal_messages", "portal_message_receipts", "portal_message_attachments",
    "portal_document_requests", "document_versions", "portal_notifications", "signature_requests",
)

def upgrade():
    op.create_table("portal_accounts", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("person_id", sa.Integer(), sa.ForeignKey("people.id", ondelete="CASCADE"), nullable=False), sa.Column("email", sa.String(320), nullable=False), sa.Column("normalized_email", sa.String(320), nullable=False, unique=True), sa.Column("display_name", sa.String(255), nullable=False), sa.Column("auth_subject", sa.String(500), unique=True), sa.Column("status", sa.String(30), nullable=False, server_default="invited"), sa.Column("mfa_enabled", sa.Boolean(), nullable=False, server_default="false"), sa.Column("mfa_required", sa.Boolean(), nullable=False, server_default="true"), sa.Column("last_login_at", sa.DateTime(timezone=True)), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()))
    op.create_table("portal_access_grants", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("portal_account_id", sa.Integer(), sa.ForeignKey("portal_accounts.id", ondelete="CASCADE"), nullable=False), sa.Column("household_id", sa.Integer(), sa.ForeignKey("households.id", ondelete="CASCADE"), nullable=False), sa.Column("person_id", sa.Integer(), sa.ForeignKey("people.id", ondelete="CASCADE")), sa.Column("access_type", sa.String(30), nullable=False), sa.Column("permissions", sa.JSON(), nullable=False, server_default="{}"), sa.Column("effective_date", sa.Date(), nullable=False, server_default=sa.func.current_date()), sa.Column("inactive_date", sa.Date()), sa.Column("granted_by_user_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="SET NULL")), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()), sa.UniqueConstraint("portal_account_id", "household_id", "person_id", "access_type", "effective_date", name="uq_portal_access_grant"))
    op.create_table("portal_invitations", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("portal_account_id", sa.Integer(), sa.ForeignKey("portal_accounts.id", ondelete="CASCADE"), nullable=False), sa.Column("token_hash", sa.String(64), nullable=False, unique=True), sa.Column("invited_by_user_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="SET NULL")), sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False), sa.Column("accepted_at", sa.DateTime(timezone=True)), sa.Column("revoked_at", sa.DateTime(timezone=True)), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()))
    op.create_table("portal_auth_tokens", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("portal_account_id", sa.Integer(), sa.ForeignKey("portal_accounts.id", ondelete="CASCADE"), nullable=False), sa.Column("token_type", sa.String(30), nullable=False), sa.Column("token_hash", sa.String(64), nullable=False, unique=True), sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False), sa.Column("used_at", sa.DateTime(timezone=True)), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()))
    op.create_table("portal_devices", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("portal_account_id", sa.Integer(), sa.ForeignKey("portal_accounts.id", ondelete="CASCADE"), nullable=False), sa.Column("fingerprint_hash", sa.String(64), nullable=False), sa.Column("name", sa.String(255)), sa.Column("trusted", sa.Boolean(), nullable=False, server_default="false"), sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()), sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()), sa.UniqueConstraint("portal_account_id", "fingerprint_hash", name="uq_portal_device"))
    op.create_table("portal_sessions", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("portal_account_id", sa.Integer(), sa.ForeignKey("portal_accounts.id", ondelete="CASCADE"), nullable=False), sa.Column("session_hash", sa.String(64), nullable=False, unique=True), sa.Column("device_id", sa.Integer(), sa.ForeignKey("portal_devices.id", ondelete="SET NULL")), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()), sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False), sa.Column("revoked_at", sa.DateTime(timezone=True)), sa.Column("last_seen_at", sa.DateTime(timezone=True)), sa.Column("ip_address", sa.String(100)), sa.Column("user_agent", sa.String(1000)))
    op.create_table("portal_threads", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("household_id", sa.Integer(), sa.ForeignKey("households.id", ondelete="CASCADE"), nullable=False), sa.Column("person_id", sa.Integer(), sa.ForeignKey("people.id", ondelete="SET NULL")), sa.Column("subject", sa.String(255), nullable=False), sa.Column("status", sa.String(30), nullable=False, server_default="open"), sa.Column("created_by_portal_account_id", sa.Integer(), sa.ForeignKey("portal_accounts.id", ondelete="SET NULL")), sa.Column("created_by_user_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="SET NULL")), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()))
    op.create_table("portal_thread_participants", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("thread_id", sa.Integer(), sa.ForeignKey("portal_threads.id", ondelete="CASCADE"), nullable=False), sa.Column("portal_account_id", sa.Integer(), sa.ForeignKey("portal_accounts.id", ondelete="CASCADE")), sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="CASCADE")), sa.Column("participant_role", sa.String(30), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()), sa.CheckConstraint("portal_account_id IS NOT NULL OR user_id IS NOT NULL", name="ck_portal_thread_participant"))
    op.create_table("portal_messages", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("thread_id", sa.Integer(), sa.ForeignKey("portal_threads.id", ondelete="CASCADE"), nullable=False), sa.Column("sender_portal_account_id", sa.Integer(), sa.ForeignKey("portal_accounts.id", ondelete="SET NULL")), sa.Column("sender_user_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="SET NULL")), sa.Column("body", sa.Text(), nullable=False), sa.Column("visibility", sa.String(30), nullable=False, server_default="client"), sa.Column("status", sa.String(30), nullable=False, server_default="sent"), sa.Column("sent_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()), sa.Column("edited_at", sa.DateTime(timezone=True)), sa.CheckConstraint("sender_portal_account_id IS NOT NULL OR sender_user_id IS NOT NULL", name="ck_portal_message_sender"))
    op.create_table("portal_message_receipts", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("message_id", sa.Integer(), sa.ForeignKey("portal_messages.id", ondelete="CASCADE"), nullable=False), sa.Column("portal_account_id", sa.Integer(), sa.ForeignKey("portal_accounts.id", ondelete="CASCADE")), sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="CASCADE")), sa.Column("read_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()), sa.CheckConstraint("portal_account_id IS NOT NULL OR user_id IS NOT NULL", name="ck_portal_receipt_reader"), sa.UniqueConstraint("message_id", "portal_account_id", "user_id", name="uq_portal_message_receipt"))
    op.create_table("portal_message_attachments", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("message_id", sa.Integer(), sa.ForeignKey("portal_messages.id", ondelete="CASCADE"), nullable=False), sa.Column("document_id", sa.Integer(), sa.ForeignKey("documents.id", ondelete="CASCADE"), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()), sa.UniqueConstraint("message_id", "document_id", name="uq_portal_message_attachment"))
    op.create_table("portal_document_requests", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("person_id", sa.Integer(), sa.ForeignKey("people.id", ondelete="CASCADE"), nullable=False), sa.Column("household_id", sa.Integer(), sa.ForeignKey("households.id", ondelete="CASCADE"), nullable=False), sa.Column("workflow_instance_id", sa.Integer(), sa.ForeignKey("workflow_instances.id", ondelete="SET NULL")), sa.Column("workflow_step_id", sa.Integer(), sa.ForeignKey("workflow_steps.id", ondelete="SET NULL")), sa.Column("title", sa.String(255), nullable=False), sa.Column("description", sa.Text()), sa.Column("due_date", sa.Date()), sa.Column("status", sa.String(30), nullable=False, server_default="open"), sa.Column("uploaded_document_id", sa.Integer(), sa.ForeignKey("documents.id", ondelete="SET NULL")), sa.Column("requested_by_user_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="SET NULL")), sa.Column("approved_by_user_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="SET NULL")), sa.Column("uploaded_at", sa.DateTime(timezone=True)), sa.Column("approved_at", sa.DateTime(timezone=True)), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()))
    op.create_table("document_versions", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("document_id", sa.Integer(), sa.ForeignKey("documents.id", ondelete="CASCADE"), nullable=False), sa.Column("version_number", sa.Integer(), nullable=False), sa.Column("previous_document_id", sa.Integer(), sa.ForeignKey("documents.id", ondelete="SET NULL")), sa.Column("uploaded_by_portal_account_id", sa.Integer(), sa.ForeignKey("portal_accounts.id", ondelete="SET NULL")), sa.Column("uploaded_by_user_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="SET NULL")), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()), sa.UniqueConstraint("document_id", "version_number", name="uq_document_version"))
    op.create_table("portal_notifications", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("portal_account_id", sa.Integer(), sa.ForeignKey("portal_accounts.id", ondelete="CASCADE"), nullable=False), sa.Column("channel", sa.String(30), nullable=False, server_default="in_app"), sa.Column("notification_type", sa.String(100), nullable=False), sa.Column("title", sa.String(255), nullable=False), sa.Column("body", sa.Text()), sa.Column("status", sa.String(30), nullable=False, server_default="delivered"), sa.Column("entity_type", sa.String(50)), sa.Column("entity_id", sa.Integer()), sa.Column("idempotency_key", sa.String(255), nullable=False, unique=True), sa.Column("delivery_metadata", sa.JSON(), nullable=False, server_default="{}"), sa.Column("read_at", sa.DateTime(timezone=True)), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()))
    op.create_table("signature_requests", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("provider_key", sa.String(100), nullable=False), sa.Column("external_id", sa.String(500)), sa.Column("person_id", sa.Integer(), sa.ForeignKey("people.id", ondelete="CASCADE"), nullable=False), sa.Column("household_id", sa.Integer(), sa.ForeignKey("households.id", ondelete="CASCADE")), sa.Column("workflow_instance_id", sa.Integer(), sa.ForeignKey("workflow_instances.id", ondelete="SET NULL")), sa.Column("workflow_step_id", sa.Integer(), sa.ForeignKey("workflow_steps.id", ondelete="SET NULL")), sa.Column("status", sa.String(30), nullable=False, server_default="draft"), sa.Column("request_payload", sa.JSON(), nullable=False, server_default="{}"), sa.Column("requested_by_user_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="SET NULL")), sa.Column("completed_at", sa.DateTime(timezone=True)), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()), sa.UniqueConstraint("provider_key", "external_id", name="uq_signature_provider_external"))
    op.create_index("ix_portal_messages_thread_sent", "portal_messages", ["thread_id", "sent_at"])
    op.create_index("ix_portal_requests_household_status", "portal_document_requests", ["household_id", "status"])
    op.execute("CREATE FUNCTION prevent_portal_message_mutation() RETURNS trigger AS $$ BEGIN RAISE EXCEPTION 'portal messages are append-only'; END; $$ LANGUAGE plpgsql")
    op.execute("CREATE TRIGGER portal_messages_immutable BEFORE UPDATE OR DELETE ON portal_messages FOR EACH ROW EXECUTE FUNCTION prevent_portal_message_mutation()")
    op.execute("CREATE FUNCTION prevent_portal_receipt_mutation() RETURNS trigger AS $$ BEGIN RAISE EXCEPTION 'portal read receipts are append-only'; END; $$ LANGUAGE plpgsql")
    op.execute("CREATE TRIGGER portal_receipts_immutable BEFORE UPDATE OR DELETE ON portal_message_receipts FOR EACH ROW EXECUTE FUNCTION prevent_portal_receipt_mutation()")

def downgrade():
    op.execute("DROP TRIGGER IF EXISTS portal_receipts_immutable ON portal_message_receipts"); op.execute("DROP FUNCTION IF EXISTS prevent_portal_receipt_mutation()")
    op.execute("DROP TRIGGER IF EXISTS portal_messages_immutable ON portal_messages"); op.execute("DROP FUNCTION IF EXISTS prevent_portal_message_mutation()")
    for name in reversed(TABLES): op.drop_table(name)
