"""add tax domain foundation

Revision ID: g750b7d5f6a7
Revises: f640a6c4e5f6
"""
from datetime import datetime, timezone
from alembic import op
import sqlalchemy as sa

revision = "g750b7d5f6a7"
down_revision = "f640a6c4e5f6"
branch_labels = None
depends_on = None

TABLES = ("tax_firms", "tax_offices", "tax_office_memberships", "tax_years",
    "filing_jurisdictions", "tax_return_types", "tax_filing_statuses", "tax_seasons",
    "tax_calendars", "tax_deadline_rules", "tax_engagements", "tax_engagement_returns",
    "tax_deadlines", "tax_workflow_links")

def upgrade():
    op.create_table("tax_firms", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("code", sa.String(100), nullable=False, unique=True), sa.Column("name", sa.String(255), nullable=False), sa.Column("active", sa.Boolean(), nullable=False, server_default="true"), sa.Column("settings", sa.JSON(), nullable=False, server_default="{}"), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()))
    op.create_table("tax_offices", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("tax_firm_id", sa.Integer(), sa.ForeignKey("tax_firms.id", ondelete="CASCADE"), nullable=False), sa.Column("code", sa.String(100), nullable=False), sa.Column("name", sa.String(255), nullable=False), sa.Column("timezone", sa.String(100), nullable=False, server_default="America/New_York"), sa.Column("active", sa.Boolean(), nullable=False, server_default="true"), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()), sa.UniqueConstraint("tax_firm_id", "code", name="uq_tax_office_code"))
    op.create_table("tax_office_memberships", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("tax_office_id", sa.Integer(), sa.ForeignKey("tax_offices.id", ondelete="CASCADE"), nullable=False), sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("tax_role", sa.String(30), nullable=False), sa.Column("capacity_minutes", sa.Integer(), nullable=False, server_default="480"), sa.Column("effective_date", sa.Date(), nullable=False, server_default=sa.func.current_date()), sa.Column("inactive_date", sa.Date()), sa.UniqueConstraint("tax_office_id", "user_id", "tax_role", "effective_date", name="uq_tax_office_membership"))
    op.create_table("tax_years", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("year", sa.Integer(), nullable=False, unique=True), sa.Column("starts_on", sa.Date(), nullable=False), sa.Column("ends_on", sa.Date(), nullable=False), sa.Column("status", sa.String(30), nullable=False, server_default="open"), sa.CheckConstraint("starts_on <= ends_on", name="ck_tax_year_range"))
    op.create_table("filing_jurisdictions", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("code", sa.String(50), nullable=False, unique=True), sa.Column("name", sa.String(255), nullable=False), sa.Column("level", sa.String(30), nullable=False), sa.Column("country_code", sa.String(2), nullable=False, server_default="US"), sa.Column("parent_id", sa.Integer(), sa.ForeignKey("filing_jurisdictions.id", ondelete="SET NULL")), sa.Column("active", sa.Boolean(), nullable=False, server_default="true"))
    op.create_table("tax_return_types", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("code", sa.String(50), nullable=False, unique=True), sa.Column("name", sa.String(255), nullable=False), sa.Column("entity_type", sa.String(30), nullable=False), sa.Column("form_number", sa.String(50)), sa.Column("workflow_template_code", sa.String(100)), sa.Column("active", sa.Boolean(), nullable=False, server_default="true"))
    op.create_table("tax_filing_statuses", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("code", sa.String(50), nullable=False, unique=True), sa.Column("name", sa.String(255), nullable=False), sa.Column("applies_to_entity_type", sa.String(30), nullable=False, server_default="individual"), sa.Column("active", sa.Boolean(), nullable=False, server_default="true"))
    op.create_table("tax_seasons", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("tax_firm_id", sa.Integer(), sa.ForeignKey("tax_firms.id", ondelete="CASCADE"), nullable=False), sa.Column("tax_year_id", sa.Integer(), sa.ForeignKey("tax_years.id", ondelete="CASCADE"), nullable=False), sa.Column("name", sa.String(255), nullable=False), sa.Column("starts_on", sa.Date(), nullable=False), sa.Column("ends_on", sa.Date(), nullable=False), sa.Column("status", sa.String(30), nullable=False, server_default="planned"), sa.Column("capacity_multiplier", sa.Numeric(5,2), nullable=False, server_default="1.00"), sa.UniqueConstraint("tax_firm_id", "tax_year_id", name="uq_tax_season_year"))
    op.create_table("tax_calendars", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("tax_firm_id", sa.Integer(), sa.ForeignKey("tax_firms.id", ondelete="CASCADE"), nullable=False), sa.Column("tax_office_id", sa.Integer(), sa.ForeignKey("tax_offices.id", ondelete="CASCADE")), sa.Column("name", sa.String(255), nullable=False), sa.Column("timezone", sa.String(100), nullable=False, server_default="America/New_York"), sa.Column("holiday_policy", sa.JSON(), nullable=False, server_default="{}"), sa.Column("active", sa.Boolean(), nullable=False, server_default="true"))
    op.create_table("tax_deadline_rules", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("jurisdiction_id", sa.Integer(), sa.ForeignKey("filing_jurisdictions.id", ondelete="CASCADE"), nullable=False), sa.Column("return_type_id", sa.Integer(), sa.ForeignKey("tax_return_types.id", ondelete="CASCADE"), nullable=False), sa.Column("version", sa.Integer(), nullable=False), sa.Column("rule_code", sa.String(100), nullable=False), sa.Column("month", sa.Integer(), nullable=False), sa.Column("day", sa.Integer(), nullable=False), sa.Column("extension_months", sa.Integer(), nullable=False, server_default="0"), sa.Column("weekend_policy", sa.String(30), nullable=False, server_default="next_business_day"), sa.Column("authority", sa.Text()), sa.Column("effective_from", sa.Date(), nullable=False), sa.Column("effective_to", sa.Date()), sa.Column("published", sa.Boolean(), nullable=False, server_default="false"), sa.UniqueConstraint("jurisdiction_id", "return_type_id", "rule_code", "version", name="uq_tax_deadline_rule_version"))
    op.create_table("tax_engagements", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("tax_firm_id", sa.Integer(), sa.ForeignKey("tax_firms.id", ondelete="RESTRICT"), nullable=False), sa.Column("tax_office_id", sa.Integer(), sa.ForeignKey("tax_offices.id", ondelete="RESTRICT"), nullable=False), sa.Column("tax_year_id", sa.Integer(), sa.ForeignKey("tax_years.id", ondelete="RESTRICT"), nullable=False), sa.Column("person_id", sa.Integer(), sa.ForeignKey("people.id", ondelete="CASCADE")), sa.Column("household_id", sa.Integer(), sa.ForeignKey("households.id", ondelete="CASCADE")), sa.Column("relationship_entity_id", sa.Integer(), sa.ForeignKey("relationship_entities.id", ondelete="CASCADE")), sa.Column("engagement_type", sa.String(30), nullable=False), sa.Column("status", sa.String(30), nullable=False, server_default="active"), sa.Column("opened_on", sa.Date(), nullable=False, server_default=sa.func.current_date()), sa.Column("closed_on", sa.Date()), sa.Column("metadata", sa.JSON(), nullable=False, server_default="{}"), sa.Column("created_by_user_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="SET NULL")), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()), sa.CheckConstraint("person_id IS NOT NULL OR relationship_entity_id IS NOT NULL", name="ck_tax_engagement_subject"))
    op.create_table("tax_engagement_returns", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("tax_engagement_id", sa.Integer(), sa.ForeignKey("tax_engagements.id", ondelete="CASCADE"), nullable=False), sa.Column("return_type_id", sa.Integer(), sa.ForeignKey("tax_return_types.id", ondelete="RESTRICT"), nullable=False), sa.Column("jurisdiction_id", sa.Integer(), sa.ForeignKey("filing_jurisdictions.id", ondelete="RESTRICT"), nullable=False), sa.Column("filing_status_id", sa.Integer(), sa.ForeignKey("tax_filing_statuses.id", ondelete="SET NULL")), sa.Column("status", sa.String(30), nullable=False, server_default="not_started"), sa.Column("priority", sa.String(30), nullable=False, server_default="normal"), sa.Column("external_key", sa.String(255)), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()), sa.UniqueConstraint("tax_engagement_id", "return_type_id", "jurisdiction_id", name="uq_tax_engagement_return"))
    op.create_table("tax_deadlines", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("tax_engagement_return_id", sa.Integer(), sa.ForeignKey("tax_engagement_returns.id", ondelete="CASCADE"), nullable=False), sa.Column("deadline_rule_id", sa.Integer(), sa.ForeignKey("tax_deadline_rules.id", ondelete="RESTRICT"), nullable=False), sa.Column("deadline_type", sa.String(30), nullable=False, server_default="original"), sa.Column("due_date", sa.Date(), nullable=False), sa.Column("calculated_due_date", sa.Date(), nullable=False), sa.Column("override_reason", sa.Text()), sa.Column("overridden_by_user_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="SET NULL")), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()), sa.UniqueConstraint("tax_engagement_return_id", "deadline_type", name="uq_tax_return_deadline"))
    op.create_table("tax_workflow_links", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("tax_engagement_return_id", sa.Integer(), sa.ForeignKey("tax_engagement_returns.id", ondelete="CASCADE"), nullable=False), sa.Column("workflow_instance_id", sa.Integer(), sa.ForeignKey("workflow_instances.id", ondelete="CASCADE"), nullable=False), sa.Column("link_type", sa.String(30), nullable=False, server_default="primary"), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()), sa.UniqueConstraint("tax_engagement_return_id", "workflow_instance_id", name="uq_tax_workflow_link"))
    op.create_index("ix_tax_engagement_scope", "tax_engagements", ["tax_office_id", "tax_year_id", "status"])
    op.create_index("ix_tax_deadlines_due", "tax_deadlines", ["due_date", "deadline_type"])
    bind = op.get_bind()
    firm_id = bind.execute(sa.text("INSERT INTO tax_firms(code,name) VALUES ('360-tax','360 Tax Solutions') RETURNING id")).scalar_one()
    office_id = bind.execute(sa.text("INSERT INTO tax_offices(tax_firm_id,code,name) VALUES (:f,'primary','Primary Office') RETURNING id"), {"f": firm_id}).scalar_one()
    federal_id = bind.execute(sa.text("INSERT INTO filing_jurisdictions(code,name,level) VALUES ('US','United States','federal') RETURNING id")).scalar_one()
    types = (("1040","Individual Income Tax","individual","1040"),("1065","Partnership Return","business","1065"),("1120","Corporate Income Tax","business","1120"),("1120S","S Corporation Return","business","1120-S"),("1041","Fiduciary Income Tax","trust_estate","1041"),("706","Estate Tax","estate","706"),("990","Exempt Organization","nonprofit","990"),("941","Payroll Tax","payroll","941"))
    for code,name,entity,form in types: bind.execute(sa.text("INSERT INTO tax_return_types(code,name,entity_type,form_number,workflow_template_code) VALUES (:c,:n,:e,:f,'tax_engagement_foundation')"), {"c":code,"n":name,"e":entity,"f":form})
    due_dates = {"1040": (4,15,6), "1065": (3,15,6), "1120": (4,15,6), "1120S": (3,15,6), "1041": (4,15,6), "706": (9,30,6), "990": (5,15,6), "941": (4,30,0)}
    for code,(month,day,extension) in due_dates.items():
        bind.execute(sa.text("INSERT INTO tax_deadline_rules(jurisdiction_id,return_type_id,version,rule_code,month,day,extension_months,authority,effective_from,published) SELECT :j,id,1,'annual-original',:m,:d,:x,'Configured baseline; verify annually','2020-01-01',true FROM tax_return_types WHERE code=:c"), {"j":federal_id,"m":month,"d":day,"x":extension,"c":code})
    for code,name in (("single","Single"),("mfj","Married Filing Jointly"),("mfs","Married Filing Separately"),("hoh","Head of Household"),("qw","Qualifying Surviving Spouse"),("na","Not Applicable")): bind.execute(sa.text("INSERT INTO tax_filing_statuses(code,name) VALUES (:c,:n)"), {"c":code,"n":name})
    for code,name,criteria in (("tax_unassigned","Tax — Unassigned",'{"unassigned":true,"work_type":"tax"}'),("tax_deadline_risk","Tax — Deadline Risk",'{"work_type":"tax","sla_risk":true}'),("tax_ready_to_prepare","Tax — Ready to Prepare",'{"work_type":"tax","status":"ready_to_prepare"}'),("tax_manager_review","Tax — Manager Review",'{"work_type":"tax","status":"manager_review"}'),("tax_partner_review","Tax — Partner Review",'{"work_type":"tax","status":"partner_review"}')): bind.execute(sa.text("INSERT INTO work_queues(code,name,description,criteria,required_capability) VALUES (:c,:n,:n,CAST(:x AS json),'tax.read')"), {"c":code,"n":name,"x":criteria})
    for code,desc,sensitive in (("tax.read","View authorized tax work",False),("tax.write","Create and update authorized tax work",False),("tax.deadline.manage","Override tax deadlines",True),("tax.review","Review authorized tax returns",True)): bind.execute(sa.text("INSERT INTO capabilities(code,description,sensitive) VALUES (:c,:d,:s)"), {"c":code,"d":desc,"s":sensitive})
    bind.execute(sa.text("INSERT INTO role_capabilities(role_id,capability_id) SELECT r.id,c.id FROM roles r CROSS JOIN capabilities c WHERE r.code='administrator' AND c.code LIKE 'tax.%'"))
    template_id = bind.execute(sa.text("INSERT INTO workflow_templates(code,version,name,category,status,default_sla_hours) VALUES ('tax_engagement_foundation',1,'Tax Engagement Foundation','tax','draft',720) RETURNING id")).scalar_one()
    step_ids = []
    for key,name,seq,waiting,approval in (("intake","Confirm engagement scope",10,"client",False),("documents","Collect tax documents",20,"client",False),("prepare","Prepare return",30,None,False),("review","Independent reviewer approval",40,None,True),("file","Authorize filing",50,"client",False)):
        step_ids.append(bind.execute(sa.text("INSERT INTO workflow_template_steps(template_id,step_key,name,sequence,step_type,queue_code,requires_independent_approval,assignment_config) VALUES (:t,:k,:n,:s,:type,:q,:a,CAST(:cfg AS json)) RETURNING id"), {"t":template_id,"k":key,"n":name,"s":seq,"type":"approval" if approval else "task","q":"waiting_on_client" if waiting else None,"a":approval,"cfg":'{"audience":"client"}' if waiting else '{}'}).scalar_one())
    for current,previous in zip(step_ids[1:],step_ids[:-1]): bind.execute(sa.text("INSERT INTO workflow_step_dependencies(step_id,depends_on_step_id) VALUES (:s,:d)"), {"s":current,"d":previous})
    bind.execute(sa.text("UPDATE workflow_templates SET status='published',published_at=:now WHERE id=:id"), {"now":datetime.now(timezone.utc),"id":template_id})

def downgrade():
    bind = op.get_bind()
    # Tax assignments have polymorphic targets rather than foreign keys; remove
    # only Sprint 5.1-owned targets so reused integer IDs cannot inherit them.
    op.execute("UPDATE record_assignments SET inactive_date = CURRENT_DATE - 1 WHERE entity_type IN ('tax_engagement','tax_return') AND (inactive_date IS NULL OR inactive_date >= CURRENT_DATE)")
    op.execute("DELETE FROM role_capabilities WHERE capability_id IN (SELECT id FROM capabilities WHERE code LIKE 'tax.%')")
    op.execute("DELETE FROM capabilities WHERE code LIKE 'tax.%'")
    op.execute("DELETE FROM work_queues WHERE code LIKE 'tax_%'")
    template_id = bind.scalar(sa.text("SELECT id FROM workflow_templates WHERE code='tax_engagement_foundation' AND version=1"))
    if template_id:
        # Preserve launched workflow instances and their immutable snapshots when
        # rolling back the Sprint 5.1 template definition.
        op.execute("UPDATE workflow_instances SET template_id = NULL WHERE template_id = %d" % template_id)
        op.execute("ALTER TABLE workflow_templates DISABLE TRIGGER workflow_templates_published_immutable")
        op.execute("ALTER TABLE workflow_template_steps DISABLE TRIGGER workflow_template_steps_published_immutable")
        op.execute("ALTER TABLE workflow_step_dependencies DISABLE TRIGGER workflow_dependencies_delete_immutable")
        op.execute("DELETE FROM workflow_step_dependencies WHERE step_id IN (SELECT id FROM workflow_template_steps WHERE template_id = %d)" % template_id)
        op.execute("DELETE FROM workflow_template_steps WHERE template_id = %d" % template_id)
        op.execute("DELETE FROM workflow_templates WHERE id = %d" % template_id)
        op.execute("ALTER TABLE workflow_step_dependencies ENABLE TRIGGER workflow_dependencies_delete_immutable")
        op.execute("ALTER TABLE workflow_template_steps ENABLE TRIGGER workflow_template_steps_published_immutable")
        op.execute("ALTER TABLE workflow_templates ENABLE TRIGGER workflow_templates_published_immutable")
    for name in reversed(TABLES): op.drop_table(name)
