"""add tax engagement intake and client collaboration

Revision ID: h860c8e6a7b8
Revises: g750b7d5f6a7
"""
from alembic import op
import sqlalchemy as sa

revision = "h860c8e6a7b8"
down_revision = "g750b7d5f6a7"
branch_labels = None
depends_on = None

TABLES = ("engagement_letter_templates", "tax_engagement_letters", "tax_organizer_templates",
    "tax_organizers", "tax_questionnaire_templates", "tax_questionnaire_questions",
    "tax_questionnaires", "tax_questionnaire_answers", "tax_checklist_templates",
    "tax_checklist_template_items", "tax_checklist_items", "tax_missing_items")

def upgrade():
    op.create_table("engagement_letter_templates", sa.Column("id",sa.Integer(),primary_key=True), sa.Column("code",sa.String(100),nullable=False), sa.Column("version",sa.Integer(),nullable=False), sa.Column("name",sa.String(255),nullable=False), sa.Column("audience",sa.String(30),nullable=False), sa.Column("body",sa.Text(),nullable=False), sa.Column("status",sa.String(30),nullable=False,server_default="draft"), sa.Column("published_at",sa.DateTime(timezone=True)), sa.Column("created_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()), sa.UniqueConstraint("code","version",name="uq_engagement_letter_template_version"))
    op.create_table("tax_engagement_letters", sa.Column("id",sa.Integer(),primary_key=True), sa.Column("tax_engagement_id",sa.Integer(),sa.ForeignKey("tax_engagements.id",ondelete="CASCADE"),nullable=False), sa.Column("template_id",sa.Integer(),sa.ForeignKey("engagement_letter_templates.id",ondelete="RESTRICT")), sa.Column("template_snapshot",sa.JSON(),nullable=False), sa.Column("status",sa.String(30),nullable=False,server_default="pending"), sa.Column("accepted_by_portal_account_id",sa.Integer(),sa.ForeignKey("portal_accounts.id",ondelete="SET NULL")), sa.Column("accepted_at",sa.DateTime(timezone=True)), sa.Column("acceptance_metadata",sa.JSON(),nullable=False,server_default="{}"), sa.Column("created_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()), sa.UniqueConstraint("tax_engagement_id",name="uq_tax_engagement_letter"))
    op.create_table("tax_organizer_templates", sa.Column("id",sa.Integer(),primary_key=True), sa.Column("code",sa.String(100),nullable=False), sa.Column("version",sa.Integer(),nullable=False), sa.Column("name",sa.String(255),nullable=False), sa.Column("audience",sa.String(30),nullable=False), sa.Column("return_type_id",sa.Integer(),sa.ForeignKey("tax_return_types.id",ondelete="CASCADE")), sa.Column("definition",sa.JSON(),nullable=False,server_default="{}"), sa.Column("status",sa.String(30),nullable=False,server_default="draft"), sa.Column("published_at",sa.DateTime(timezone=True)), sa.UniqueConstraint("code","version",name="uq_tax_organizer_template_version"))
    op.create_table("tax_organizers", sa.Column("id",sa.Integer(),primary_key=True), sa.Column("tax_engagement_return_id",sa.Integer(),sa.ForeignKey("tax_engagement_returns.id",ondelete="CASCADE"),nullable=False), sa.Column("template_id",sa.Integer(),sa.ForeignKey("tax_organizer_templates.id",ondelete="RESTRICT")), sa.Column("template_snapshot",sa.JSON(),nullable=False), sa.Column("tax_year",sa.Integer(),nullable=False), sa.Column("status",sa.String(30),nullable=False,server_default="not_started"), sa.Column("responses",sa.JSON(),nullable=False,server_default="{}"), sa.Column("progress_percent",sa.Integer(),nullable=False,server_default="0"), sa.Column("started_at",sa.DateTime(timezone=True)), sa.Column("completed_at",sa.DateTime(timezone=True)), sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()), sa.UniqueConstraint("tax_engagement_return_id",name="uq_tax_return_organizer"))
    op.create_table("tax_questionnaire_templates", sa.Column("id",sa.Integer(),primary_key=True), sa.Column("code",sa.String(100),nullable=False), sa.Column("version",sa.Integer(),nullable=False), sa.Column("name",sa.String(255),nullable=False), sa.Column("audience",sa.String(30),nullable=False), sa.Column("status",sa.String(30),nullable=False,server_default="draft"), sa.Column("published_at",sa.DateTime(timezone=True)), sa.UniqueConstraint("code","version",name="uq_tax_questionnaire_template_version"))
    op.create_table("tax_questionnaire_questions", sa.Column("id",sa.Integer(),primary_key=True), sa.Column("template_id",sa.Integer(),sa.ForeignKey("tax_questionnaire_templates.id",ondelete="CASCADE"),nullable=False), sa.Column("question_key",sa.String(100),nullable=False), sa.Column("prompt",sa.Text(),nullable=False), sa.Column("response_type",sa.String(30),nullable=False,server_default="text"), sa.Column("required",sa.Boolean(),nullable=False,server_default="false"), sa.Column("sequence",sa.Integer(),nullable=False), sa.Column("condition",sa.JSON(),nullable=False,server_default="{}"), sa.Column("configuration",sa.JSON(),nullable=False,server_default="{}"), sa.UniqueConstraint("template_id","question_key",name="uq_tax_questionnaire_question"))
    op.create_table("tax_questionnaires", sa.Column("id",sa.Integer(),primary_key=True), sa.Column("tax_engagement_return_id",sa.Integer(),sa.ForeignKey("tax_engagement_returns.id",ondelete="CASCADE"),nullable=False), sa.Column("template_id",sa.Integer(),sa.ForeignKey("tax_questionnaire_templates.id",ondelete="RESTRICT")), sa.Column("template_snapshot",sa.JSON(),nullable=False), sa.Column("status",sa.String(30),nullable=False,server_default="not_started"), sa.Column("progress_percent",sa.Integer(),nullable=False,server_default="0"), sa.Column("started_at",sa.DateTime(timezone=True)), sa.Column("completed_at",sa.DateTime(timezone=True)), sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()), sa.UniqueConstraint("tax_engagement_return_id",name="uq_tax_return_questionnaire"))
    op.create_table("tax_questionnaire_answers", sa.Column("id",sa.Integer(),primary_key=True), sa.Column("questionnaire_id",sa.Integer(),sa.ForeignKey("tax_questionnaires.id",ondelete="CASCADE"),nullable=False), sa.Column("question_key",sa.String(100),nullable=False), sa.Column("value",sa.JSON(),nullable=False), sa.Column("answered_by_portal_account_id",sa.Integer(),sa.ForeignKey("portal_accounts.id",ondelete="SET NULL")), sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()), sa.UniqueConstraint("questionnaire_id","question_key",name="uq_tax_questionnaire_answer"))
    op.create_table("tax_checklist_templates", sa.Column("id",sa.Integer(),primary_key=True), sa.Column("code",sa.String(100),nullable=False), sa.Column("version",sa.Integer(),nullable=False), sa.Column("name",sa.String(255),nullable=False), sa.Column("return_type_id",sa.Integer(),sa.ForeignKey("tax_return_types.id",ondelete="CASCADE"),nullable=False), sa.Column("status",sa.String(30),nullable=False,server_default="draft"), sa.Column("published_at",sa.DateTime(timezone=True)), sa.UniqueConstraint("code","version",name="uq_tax_checklist_template_version"))
    op.create_table("tax_checklist_template_items", sa.Column("id",sa.Integer(),primary_key=True), sa.Column("template_id",sa.Integer(),sa.ForeignKey("tax_checklist_templates.id",ondelete="CASCADE"),nullable=False), sa.Column("item_key",sa.String(100),nullable=False), sa.Column("title",sa.String(255),nullable=False), sa.Column("description",sa.Text()), sa.Column("required",sa.Boolean(),nullable=False,server_default="true"), sa.Column("sequence",sa.Integer(),nullable=False), sa.Column("due_days",sa.Integer(),nullable=False,server_default="14"), sa.Column("condition",sa.JSON(),nullable=False,server_default="{}"), sa.UniqueConstraint("template_id","item_key",name="uq_tax_checklist_template_item"))
    op.create_table("tax_checklist_items", sa.Column("id",sa.Integer(),primary_key=True), sa.Column("tax_engagement_return_id",sa.Integer(),sa.ForeignKey("tax_engagement_returns.id",ondelete="CASCADE"),nullable=False), sa.Column("template_item_id",sa.Integer(),sa.ForeignKey("tax_checklist_template_items.id",ondelete="RESTRICT")), sa.Column("item_snapshot",sa.JSON(),nullable=False), sa.Column("status",sa.String(30),nullable=False,server_default="missing"), sa.Column("required",sa.Boolean(),nullable=False), sa.Column("due_date",sa.Date()), sa.Column("portal_document_request_id",sa.Integer(),sa.ForeignKey("portal_document_requests.id",ondelete="SET NULL")), sa.Column("document_id",sa.Integer(),sa.ForeignKey("documents.id",ondelete="SET NULL")), sa.Column("completed_at",sa.DateTime(timezone=True)), sa.UniqueConstraint("tax_engagement_return_id","template_item_id",name="uq_tax_return_checklist_item"))
    op.create_table("tax_missing_items", sa.Column("id",sa.Integer(),primary_key=True), sa.Column("tax_engagement_return_id",sa.Integer(),sa.ForeignKey("tax_engagement_returns.id",ondelete="CASCADE"),nullable=False), sa.Column("checklist_item_id",sa.Integer(),sa.ForeignKey("tax_checklist_items.id",ondelete="CASCADE")), sa.Column("item_type",sa.String(30),nullable=False), sa.Column("title",sa.String(255),nullable=False), sa.Column("description",sa.Text()), sa.Column("status",sa.String(30),nullable=False,server_default="open"), sa.Column("due_date",sa.Date()), sa.Column("reminder_count",sa.Integer(),nullable=False,server_default="0"), sa.Column("last_reminded_at",sa.DateTime(timezone=True)), sa.Column("resolved_at",sa.DateTime(timezone=True)), sa.Column("created_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()))
    op.create_index("ix_tax_intake_missing_due", "tax_missing_items", ["status","due_date"])
    op.create_index("ix_tax_checklist_status", "tax_checklist_items", ["tax_engagement_return_id","status"])
    bind=op.get_bind()
    bind.execute(sa.text("INSERT INTO engagement_letter_templates(code,version,name,audience,body,status,published_at) VALUES ('standard-tax-engagement',1,'Standard Tax Engagement','all','We agree to prepare the tax return described in this engagement using information supplied by the client.','published',now())"))
    for audience, form in (("individual","1040"),("business","1120S")):
        rt=bind.scalar(sa.text("SELECT id FROM tax_return_types WHERE code=:c"),{"c":form})
        org=bind.execute(sa.text("INSERT INTO tax_organizer_templates(code,version,name,audience,return_type_id,definition,status,published_at) VALUES (:c,1,:n,:a,:r,CAST(:d AS json),'published',now()) RETURNING id"),{"c":f"{audience}-organizer","n":f"{audience.title()} Tax Organizer","a":audience,"r":rt,"d":'{"sections":["identity","income","deductions","changes"]}' if audience=="individual" else '{"sections":["entity","ownership","income","expenses","payroll"]}'}).scalar_one()
        qt=bind.execute(sa.text("INSERT INTO tax_questionnaire_templates(code,version,name,audience,status,published_at) VALUES (:c,1,:n,:a,'published',now()) RETURNING id"),{"c":f"{audience}-intake","n":f"{audience.title()} Tax Questionnaire","a":audience}).scalar_one()
        questions=[("changes","Have there been material changes since last year?","boolean",True,10,{}),("change_details","Describe the material changes.","text",True,20,{"changes":True}),("foreign","Do you have foreign financial accounts?","boolean",True,30,{})]
        for key,prompt,response_type,required,sequence,condition in questions: bind.execute(sa.text("INSERT INTO tax_questionnaire_questions(template_id,question_key,prompt,response_type,required,sequence,condition) VALUES (:t,:k,:p,:r,:q,:s,CAST(:c AS json))"),{"t":qt,"k":key,"p":prompt,"r":response_type,"q":required,"s":sequence,"c":__import__('json').dumps(condition)})
        ct=bind.execute(sa.text("INSERT INTO tax_checklist_templates(code,version,name,return_type_id,status,published_at) VALUES (:c,1,:n,:r,'published',now()) RETURNING id"),{"c":f"{audience}-documents","n":f"{audience.title()} Tax Documents","r":rt}).scalar_one()
        items=[("prior_return","Prior-year tax return",True,10),("income","Income documents",True,20),("deductions","Deduction support",False,30)]
        for key,title,required,sequence in items: bind.execute(sa.text("INSERT INTO tax_checklist_template_items(template_id,item_key,title,required,sequence) VALUES (:t,:k,:n,:r,:s)"),{"t":ct,"k":key,"n":title,"r":required,"s":sequence})
    for code,description,sensitive in (("tax.intake.read","View authorized tax intake",False),("tax.intake.write","Manage authorized tax intake",False)):
        bind.execute(sa.text("INSERT INTO capabilities(code,description,sensitive) VALUES (:c,:d,:s)"),{"c":code,"d":description,"s":sensitive})
    bind.execute(sa.text("INSERT INTO role_capabilities(role_id,capability_id) SELECT r.id,c.id FROM roles r CROSS JOIN capabilities c WHERE r.code='administrator' AND c.code LIKE 'tax.intake.%'"))
    op.execute("CREATE FUNCTION prevent_published_tax_intake_template_mutation() RETURNS trigger AS $$ BEGIN IF OLD.status = 'published' THEN RAISE EXCEPTION 'published tax intake templates are immutable'; END IF; RETURN NEW; END; $$ LANGUAGE plpgsql")
    for table in ("engagement_letter_templates","tax_organizer_templates","tax_questionnaire_templates","tax_checklist_templates"):
        op.execute(f"CREATE TRIGGER {table}_published_immutable BEFORE UPDATE OR DELETE ON {table} FOR EACH ROW EXECUTE FUNCTION prevent_published_tax_intake_template_mutation()")
    op.execute("CREATE FUNCTION prevent_published_question_mutation() RETURNS trigger AS $$ DECLARE tid integer; BEGIN IF TG_OP='DELETE' THEN tid := OLD.template_id; ELSE tid := NEW.template_id; END IF; IF EXISTS (SELECT 1 FROM tax_questionnaire_templates WHERE id=tid AND status='published') THEN RAISE EXCEPTION 'published questionnaire questions are immutable'; END IF; IF TG_OP='DELETE' THEN RETURN OLD; END IF; RETURN NEW; END; $$ LANGUAGE plpgsql")
    op.execute("CREATE TRIGGER tax_questionnaire_questions_published_immutable BEFORE UPDATE OR DELETE ON tax_questionnaire_questions FOR EACH ROW EXECUTE FUNCTION prevent_published_question_mutation()")
    op.execute("CREATE FUNCTION prevent_published_checklist_item_mutation() RETURNS trigger AS $$ DECLARE tid integer; BEGIN IF TG_OP='DELETE' THEN tid := OLD.template_id; ELSE tid := NEW.template_id; END IF; IF EXISTS (SELECT 1 FROM tax_checklist_templates WHERE id=tid AND status='published') THEN RAISE EXCEPTION 'published checklist items are immutable'; END IF; IF TG_OP='DELETE' THEN RETURN OLD; END IF; RETURN NEW; END; $$ LANGUAGE plpgsql")
    op.execute("CREATE TRIGGER tax_checklist_template_items_published_immutable BEFORE UPDATE OR DELETE ON tax_checklist_template_items FOR EACH ROW EXECUTE FUNCTION prevent_published_checklist_item_mutation()")

def downgrade():
    op.execute("DROP TRIGGER IF EXISTS tax_checklist_template_items_published_immutable ON tax_checklist_template_items")
    op.execute("DROP FUNCTION IF EXISTS prevent_published_checklist_item_mutation()")
    op.execute("DROP TRIGGER IF EXISTS tax_questionnaire_questions_published_immutable ON tax_questionnaire_questions")
    op.execute("DROP FUNCTION IF EXISTS prevent_published_question_mutation()")
    for table in ("engagement_letter_templates","tax_organizer_templates","tax_questionnaire_templates","tax_checklist_templates"):
        op.execute(f"DROP TRIGGER IF EXISTS {table}_published_immutable ON {table}")
    op.execute("DROP FUNCTION IF EXISTS prevent_published_tax_intake_template_mutation()")
    op.execute("DELETE FROM role_capabilities WHERE capability_id IN (SELECT id FROM capabilities WHERE code LIKE 'tax.intake.%')")
    op.execute("DELETE FROM capabilities WHERE code LIKE 'tax.intake.%'")
    op.execute("DELETE FROM portal_document_requests WHERE id IN (SELECT portal_document_request_id FROM tax_checklist_items WHERE portal_document_request_id IS NOT NULL)")
    op.execute("DELETE FROM portal_notifications WHERE notification_type IN ('engagement_ready','organizer_available','missing_document','questionnaire_reminder','intake_completed') AND entity_type IN ('tax_return','tax_missing_item','tax_questionnaire')")
    for name in reversed(TABLES): op.drop_table(name)
